name: issue-needs-triage-default-label

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: "needs triage"
